// Code generated by "stringer -type=SuitType"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JokerS-0]
	_ = x[Spades-1]
	_ = x[Diamonds-2]
	_ = x[Clubs-3]
	_ = x[Hearts-4]
}

const _SuitType_name = "JokerSSpadesDiamondsClubsHearts"

var _SuitType_index = [...]uint8{0, 6, 12, 20, 25, 31}

func (i SuitType) String() string {
	if i < 0 || i >= SuitType(len(_SuitType_index)-1) {
		return "SuitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SuitType_name[_SuitType_index[i]:_SuitType_index[i+1]]
}
